spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3cca71a9a0ad0f56db1fd20b193a9074
            redirect-uri : "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri : https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/youngjae?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: dudwo123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true


  servlet:
    multipart:
      file-size-threshold: 1MB
      location: D:\files\
      max-file-size: 100MB
      max-request-size: 100MB
 # h2:
 #   console:
 #     enabled: true
 #     path: /toy
 # jpa:
 #   hibernate:
 #     ddl-auto: update
 #   properties:
 #     hibernate:
 #       show_sql: true
 #       format_sql: true
  #datasource:
  #  driver-class-name: org.h2.Driver
  #  url: jdbc:h2:tcp://localhost/~/toy
  #  username: sa
  #  password:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
files:
  files-dir: /Users/kimyoungjae/Desktop/파일폴더/
server:
  error:
    whitelabel:
      enabled: true

kakao:
  restapikey: 3cca71a9a0ad0f56db1fd20b193a9074
  redirecturl: http://localhost:8080/oauth/kakao